ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS fulfillment_status TEXT DEFAULT 'pending';
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS payout_status TEXT DEFAULT 'pending';
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS payout_released_at TIMESTAMPTZ;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS payout_held_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS payout_release_transaction_id UUID;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS tracking_last_updated_at TIMESTAMPTZ;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS estimated_delivery_date TIMESTAMPTZ;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS shipped_date TIMESTAMPTZ;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS carrier_tracking_status TEXT;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS tracking_error TEXT;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS shipping_carrier TEXT;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS tracking_number TEXT;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS tracking_url TEXT;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMPTZ;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS buyer_id UUID;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS seller_id UUID;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS item_id UUID;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS price_paid BIGINT DEFAULT 0;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS platform_fee BIGINT DEFAULT 0;
ALTER TABLE public.marketplace_purchases ADD COLUMN IF NOT EXISTS seller_earnings BIGINT DEFAULT 0;