/**
 * Profile Frame System — Configuration & Types
 * Premium animated avatar frames for Mai Troll
 */

// ─── Types ──────────────────────────────────────────────────────
export type FrameRarity =
  | 'common'
  | 'rare'
  | 'epic'
  | 'legendary'
  | 'mythic'
  | 'founder'
  | 'limited_edition';

export type AnimationType =
  | 'shimmer'
  | 'rainbow'
  | 'gold_shimmer'
  | 'diamond_sparkle'
  | 'neon_glow'
  | 'fire'
  | 'smoke'
  | 'snow'
  | 'ice'
  | 'electric'
  | 'galaxy'
  | 'crown'
  | 'trophy'
  | 'verified'
  | 'founder'
  | 'aurora'
  | 'lava'
  | 'rain'
  | 'starfall'
  | 'bubbles'
  | 'hearts'
  | 'lightning'
  | 'confetti'
  | 'matrix'
  | 'ocean'
  | 'cherry_blossom'
  | 'halloween'
  | null;

export type FrameStyle = 'flat' | 'beveled' | 'glowing' | 'animated' | 'premium' | 'legendary';

export type AnimationSpeed = 'slow' | 'normal' | 'fast';

export interface ProfileFrame {
   id: string;
   name: string;
   description: string;
   icon: string;
   animationType: AnimationType;
   frameStyle: FrameStyle;
   borderColor: string;
   borderGradient: string | null;
   glowColor: string | null;
   glowIntensity: number; // 0-2
   animationSpeed: AnimationSpeed;
   hasParticles: boolean;
   particleColor: string | null;
   particleCount: number;
   hasSparkles: boolean;
   hasEnergyRings: boolean;
   rarity: FrameRarity;
   coinCost: number;
   isActive: boolean;
   isLimited: boolean;
   limitedQuantity: number | null;
   sortOrder: number;
   frameType?: 'profile' | 'broadcast'; // 'profile' for avatar frames, 'broadcast' for stream borders
}

// ─── Rarity Colors ──────────────────────────────────────────────
export const RARITY_COLORS: Record<FrameRarity, { text: string; bg: string; border: string; glow: string }> = {
  common:         { text: '#9ca3af', bg: 'rgba(156,163,175,0.1)',  border: 'rgba(156,163,175,0.3)',  glow: 'rgba(156,163,175,0.2)' },
  rare:           { text: '#3b82f6', bg: 'rgba(59,130,246,0.1)',   border: 'rgba(59,130,246,0.3)',   glow: 'rgba(59,130,246,0.2)' },
  epic:           { text: '#a855f7', bg: 'rgba(168,85,247,0.1)',   border: 'rgba(168,85,247,0.3)',   glow: 'rgba(168,85,247,0.25)' },
  legendary:      { text: '#f59e0b', bg: 'rgba(245,158,11,0.1)',   border: 'rgba(245,158,11,0.3)',   glow: 'rgba(245,158,11,0.3)' },
  mythic:         { text: '#ec4899', bg: 'rgba(236,72,153,0.1)',   border: 'rgba(236,72,153,0.3)',   glow: 'rgba(236,72,153,0.3)' },
  founder:        { text: '#ff3366', bg: 'rgba(255,51,102,0.1)',   border: 'rgba(255,51,102,0.35)',  glow: 'rgba(255,51,102,0.35)' },
  limited_edition:{ text: '#06b6d4', bg: 'rgba(6,182,212,0.1)',    border: 'rgba(6,182,212,0.35)',   glow: 'rgba(6,182,212,0.3)' },
};

export const RARITY_LABELS: Record<FrameRarity, string> = {
  common: 'Common',
  rare: 'Rare',
  epic: 'Epic',
  legendary: 'Legendary',
  mythic: 'Mythic',
  founder: 'Founder',
  limited_edition: 'Limited Edition',
};

// ─── Animation Speed Map ────────────────────────────────────────
export const ANIMATION_DURATIONS: Record<AnimationSpeed, number> = {
  slow: 4,
  normal: 2.5,
  fast: 1.2,
};

// ─── Launch Collection ──────────────────────────────────────────
export const LAUNCH_FRAMES: ProfileFrame[] = [
  {
    id: 'pride_rainbow',
    name: 'Pride Rainbow',
    description: 'Animated flowing rainbow border celebrating pride and diversity',
    icon: '🏳️‍🌈',
    animationType: 'rainbow',
    frameStyle: 'premium',
    borderColor: '#ff0000',
    borderGradient: 'linear-gradient(90deg, #ff0000, #ff8800, #ffff00, #00ff00, #0088ff, #8800ff, #ff0000)',
    glowColor: '#ff00ff',
    glowIntensity: 0.7,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 6,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 250,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 1,
  },
  {
    id: 'gold_vip',
    name: 'Gold VIP',
    description: 'Luxury gold shimmer fit for royalty',
    icon: '👑',
    animationType: 'gold_shimmer',
    frameStyle: 'premium',
    borderColor: '#ffd700',
    borderGradient: 'linear-gradient(135deg, #ffd700, #ffaa00, #ffd700, #ffe066)',
    glowColor: '#ffd700',
    glowIntensity: 0.8,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffd700',
    particleCount: 5,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 400,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 2,
  },
  {
    id: 'diamond_elite',
    name: 'Diamond Elite',
    description: 'Sparkling crystal diamond effect with prismatic light',
    icon: '💎',
    animationType: 'diamond_sparkle',
    frameStyle: 'legendary',
    borderColor: '#00d4ff',
    borderGradient: 'linear-gradient(135deg, #00d4ff, #ffffff, #00d4ff, #80f0ff)',
    glowColor: '#00d4ff',
    glowIntensity: 1.0,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'legendary',
    coinCost: 700,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 3,
  },
  {
    id: 'neon_cyber',
    name: 'Neon Cyber',
    description: 'Rotating neon cyberpunk glow with energy rings',
    icon: '⚡',
    animationType: 'neon_glow',
    frameStyle: 'animated',
    borderColor: '#00ff88',
    borderGradient: 'linear-gradient(90deg, #00ff88, #ff00ff, #0088ff, #00ff88)',
    glowColor: '#00ff88',
    glowIntensity: 0.9,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#00ff88',
    particleCount: 6,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'epic',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 4,
  },
  {
    id: 'fire_lord',
    name: 'Fire Lord',
    description: 'Animated flames dancing around your avatar border',
    icon: '🔥',
    animationType: 'fire',
    frameStyle: 'premium',
    borderColor: '#ff4400',
    borderGradient: 'linear-gradient(135deg, #ff4400, #ff8800, #ffcc00, #ff4400)',
    glowColor: '#ff4400',
    glowIntensity: 1.0,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffcc00',
    particleCount: 7,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'legendary',
    coinCost: 800,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 5,
  },
  {
    id: 'ice_king',
    name: 'Ice King',
    description: 'Frost crystals and snow particles swirling around you',
    icon: '❄️',
    animationType: 'ice',
    frameStyle: 'premium',
    borderColor: '#88ccff',
    borderGradient: 'linear-gradient(135deg, #88ccff, #ffffff, #aaddff, #88ccff)',
    glowColor: '#88ccff',
    glowIntensity: 0.8,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 6,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'legendary',
    coinCost: 750,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 6,
  },
  {
    id: 'electric_storm',
    name: 'Electric Storm',
    description: 'Crackling lightning pulses with electric energy rings',
    icon: '⚡',
    animationType: 'electric',
    frameStyle: 'animated',
    borderColor: '#ffee00',
    borderGradient: 'linear-gradient(90deg, #ffee00, #ff8800, #ffee00, #ffff88)',
    glowColor: '#ffee00',
    glowIntensity: 1.1,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffff88',
    particleCount: 5,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'epic',
    coinCost: 600,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 7,
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    description: 'Swirling cosmic stars and nebula particles in deep space',
    icon: '🌌',
    animationType: 'galaxy',
    frameStyle: 'legendary',
    borderColor: '#8800ff',
    borderGradient: 'linear-gradient(135deg, #8800ff, #ff0088, #0088ff, #8800ff)',
    glowColor: '#8800ff',
    glowIntensity: 1.2,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#ff88ff',
    particleCount: 9,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'mythic',
    coinCost: 900,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 8,
  },
  {
    id: 'verified_creator',
    name: 'Verified Creator',
    description: 'Premium verification glow for approved creators',
    icon: '✅',
    animationType: 'verified',
    frameStyle: 'premium',
    borderColor: '#1d9bf0',
    borderGradient: 'linear-gradient(135deg, #1d9bf0, #1a8cd8, #1d9bf0)',
    glowColor: '#1d9bf0',
    glowIntensity: 0.6,
    animationSpeed: 'normal',
    hasParticles: false,
    particleColor: null,
    particleCount: 0,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 300,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 9,
  },
  {
    id: 'family_leader',
    name: 'Family Leader',
    description: 'Royal crown aura exclusive for family leaders',
    icon: '👑',
    animationType: 'crown',
    frameStyle: 'premium',
    borderColor: '#cc8800',
    borderGradient: 'linear-gradient(135deg, #cc8800, #ffcc44, #cc8800, #ffdd66)',
    glowColor: '#ffcc44',
    glowIntensity: 0.7,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffdd66',
    particleCount: 4,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 550,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 10,
  },
  {
    id: 'battle_champion',
    name: 'Battle Champion',
    description: 'Gold rotating trophy aura earned from battle victories',
    icon: '🏆',
    animationType: 'trophy',
    frameStyle: 'animated',
    borderColor: '#ffd700',
    borderGradient: 'linear-gradient(135deg, #ffd700, #b8860b, #ffd700, #daa520)',
    glowColor: '#ffd700',
    glowIntensity: 0.9,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffd700',
    particleCount: 5,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'legendary',
    coinCost: 850,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 11,
  },
  {
    id: 'troll_city_founder',
    name: 'MaiTroll Founder',
    description: 'Exclusive founder badge — only for the original trolls of the city',
    icon: '🧌',
    animationType: 'founder',
    frameStyle: 'legendary',
    borderColor: '#ff3366',
    borderGradient: 'linear-gradient(135deg, #ff3366, #ffd700, #00ff88, #ff3366)',
    glowColor: '#ff3366',
    glowIntensity: 1.5,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffd700',
    particleCount: 10,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'founder',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 12,
  },
  // ─── Visual FX Collection (all ≤ 1,000 🪙) ─────────────────────
  {
    id: 'inferno_blaze',
    name: 'Inferno Blaze',
    description: 'Real animated flames lick and dance around your avatar border with ember sparks',
    icon: '🔥',
    animationType: 'fire',
    frameStyle: 'legendary',
    borderColor: '#ff2200',
    borderGradient: 'linear-gradient(180deg, #ff6600, #ff2200, #ff8800, #ff4400, #ffcc00)',
    glowColor: '#ff4400',
    glowIntensity: 1.4,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffcc00',
    particleCount: 10,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'legendary',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 13,
  },
  {
    id: 'phantom_smoke',
    name: 'Phantom Smoke',
    description: 'Ethereal smoke wisps curl and drift around your profile picture',
    icon: '💨',
    animationType: 'smoke',
    frameStyle: 'legendary',
    borderColor: '#6b7280',
    borderGradient: 'linear-gradient(135deg, #9ca3af, #4b5563, #d1d5db, #6b7280)',
    glowColor: '#9ca3af',
    glowIntensity: 0.8,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#d1d5db',
    particleCount: 8,
    hasSparkles: false,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 800,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 14,
  },
  {
    id: 'winter_snowfall',
    name: 'Winter Snowfall',
    description: 'Gentle snowflakes drift down over your avatar inside the frame',
    icon: '❄️',
    animationType: 'snow',
    frameStyle: 'premium',
    borderColor: '#a5d8ff',
    borderGradient: 'linear-gradient(135deg, #a5d8ff, #e7f5ff, #74c0fc, #a5d8ff)',
    glowColor: '#a5d8ff',
    glowIntensity: 0.9,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 12,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 850,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 15,
  },
  {
    id: 'northern_aurora',
    name: 'Northern Aurora',
    description: 'Shimmering northern lights ripple across your frame in green and purple waves',
    icon: '🌌',
    animationType: 'aurora',
    frameStyle: 'legendary',
    borderColor: '#00cc66',
    borderGradient: 'linear-gradient(90deg, #00cc66, #8800ff, #00ffaa, #cc00ff, #00cc66)',
    glowColor: '#00ff88',
    glowIntensity: 1.1,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#88ffcc',
    particleCount: 7,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'legendary',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 16,
  },
  {
    id: 'volcanic_lava',
    name: 'Volcanic Lava',
    description: 'Molten lava flows and bubbles around your avatar with heat distortion',
    icon: '🌋',
    animationType: 'lava',
    frameStyle: 'legendary',
    borderColor: '#cc3300',
    borderGradient: 'linear-gradient(180deg, #ff6600, #cc0000, #ff4400, #990000)',
    glowColor: '#ff4400',
    glowIntensity: 1.3,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ff8800',
    particleCount: 8,
    hasSparkles: false,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 900,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 17,
  },
  {
    id: 'monsoon_rain',
    name: 'Monsoon Rain',
    description: 'Raindrops fall and splash around your profile frame with ripple effects',
    icon: '🌧️',
    animationType: 'rain',
    frameStyle: 'premium',
    borderColor: '#3b82f6',
    borderGradient: 'linear-gradient(180deg, #3b82f6, #1d4ed8, #60a5fa, #2563eb)',
    glowColor: '#60a5fa',
    glowIntensity: 0.7,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#93c5fd',
    particleCount: 10,
    hasSparkles: false,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 600,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 18,
  },
  {
    id: 'cosmic_starfall',
    name: 'Cosmic Starfall',
    description: 'Shooting stars streak across your frame with glowing trails',
    icon: '🌠',
    animationType: 'starfall',
    frameStyle: 'legendary',
    borderColor: '#7c3aed',
    borderGradient: 'linear-gradient(135deg, #7c3aed, #2563eb, #a855f7, #1d4ed8)',
    glowColor: '#a855f7',
    glowIntensity: 1.2,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#fbbf24',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'legendary',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 19,
  },
  {
    id: 'deep_sea_bubbles',
    name: 'Deep Sea Bubbles',
    description: 'Iridescent bubbles float upward around your avatar with ocean shimmer',
    icon: '🫧',
    animationType: 'bubbles',
    frameStyle: 'premium',
    borderColor: '#06b6d4',
    borderGradient: 'linear-gradient(135deg, #06b6d4, #0891b2, #22d3ee, #0e7490)',
    glowColor: '#22d3ee',
    glowIntensity: 0.8,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#a5f3fc',
    particleCount: 9,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 750,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 20,
  },
  {
    id: 'love_hearts',
    name: 'Love Hearts',
    description: 'Floating hearts drift upward around your profile with a warm pink glow',
    icon: '💕',
    animationType: 'hearts',
    frameStyle: 'premium',
    borderColor: '#ec4899',
    borderGradient: 'linear-gradient(135deg, #ec4899, #f472b6, #db2777, #f9a8d4)',
    glowColor: '#f472b6',
    glowIntensity: 0.9,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#f9a8d4',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 21,
  },
  {
    id: 'thunder_strike',
    name: 'Thunder Strike',
    description: 'Crackling lightning bolts flash and pulse around your avatar frame',
    icon: '⚡',
    animationType: 'lightning',
    frameStyle: 'animated',
    borderColor: '#fbbf24',
    borderGradient: 'linear-gradient(135deg, #fbbf24, #f59e0b, #fde68a, #d97706)',
    glowColor: '#fde68a',
    glowIntensity: 1.3,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#fef3c7',
    particleCount: 6,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'epic',
    coinCost: 900,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 22,
  },
  {
    id: 'party_confetti',
    name: 'Party Confetti',
    description: 'Colorful confetti bursts and swirls around your profile in celebration',
    icon: '🎉',
    animationType: 'confetti',
    frameStyle: 'animated',
    borderColor: '#f472b6',
    borderGradient: 'linear-gradient(90deg, #f472b6, #fbbf24, #34d399, #60a5fa, #a78bfa)',
    glowColor: '#f472b6',
    glowIntensity: 0.8,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#fbbf24',
    particleCount: 12,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 650,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 23,
  },
  {
    id: 'matrix_code',
    name: 'Matrix Code',
    description: 'Digital rain cascades down your frame in classic green matrix style',
    icon: '🟢',
    animationType: 'matrix',
    frameStyle: 'animated',
    borderColor: '#22c55e',
    borderGradient: 'linear-gradient(180deg, #22c55e, #15803d, #4ade80, #166534)',
    glowColor: '#4ade80',
    glowIntensity: 1.0,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#86efac',
    particleCount: 10,
    hasSparkles: false,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 850,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 24,
  },
  {
    id: 'ocean_waves',
    name: 'Ocean Waves',
    description: 'Flowing ocean waves lap at your frame with sea foam and shimmer',
    icon: '🌊',
    animationType: 'ocean',
    frameStyle: 'premium',
    borderColor: '#0ea5e9',
    borderGradient: 'linear-gradient(90deg, #0ea5e9, #0284c7, #38bdf8, #0369a1)',
    glowColor: '#38bdf8',
    glowIntensity: 0.9,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#bae6fd',
    particleCount: 7,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 800,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 25,
  },
  {
    id: 'sakura_blossom',
    name: 'Sakura Blossom',
    description: 'Delicate cherry blossom petals drift and spin around your avatar',
    icon: '🌸',
    animationType: 'cherry_blossom',
    frameStyle: 'premium',
    borderColor: '#f9a8d4',
    borderGradient: 'linear-gradient(135deg, #f9a8d4, #fbb6ce, #f687b3, #ed64a6)',
    glowColor: '#f687b3',
    glowIntensity: 0.7,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#fce7f3',
    particleCount: 10,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 700,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 26,
  },
  {
    id: 'haunted_halloween',
    name: 'Haunted Halloween',
    description: 'Spooky ghosts and bats float around your frame with eerie purple fog',
    icon: '🎃',
    animationType: 'halloween',
    frameStyle: 'legendary',
    borderColor: '#9333ea',
    borderGradient: 'linear-gradient(135deg, #9333ea, #581c87, #c026d3, #7e22ce)',
    glowColor: '#c084fc',
    glowIntensity: 1.1,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#e9d5ff',
    particleCount: 8,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'limited_edition',
    coinCost: 1000,
    isActive: true,
    isLimited: true,
    limitedQuantity: 500,
    sortOrder: 27,
  },
  {
    id: 'frost_crystal',
    name: 'Frost Crystal',
    description: 'Ice crystals form and shimmer on your frame with a frozen blue glow',
    icon: '🧊',
    animationType: 'ice',
    frameStyle: 'legendary',
    borderColor: '#38bdf8',
    borderGradient: 'linear-gradient(135deg, #38bdf8, #bae6fd, #0ea5e9, #7dd3fc)',
    glowColor: '#7dd3fc',
    glowIntensity: 1.0,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#e0f2fe',
    particleCount: 9,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'epic',
    coinCost: 900,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 28,
  },
  {
    id: 'neon_dreams',
    name: 'Neon Dreams',
    description: 'Vibrant neon tubes pulse and glow around your avatar in cyberpunk style',
    icon: '💜',
    animationType: 'neon_glow',
    frameStyle: 'animated',
    borderColor: '#e879f9',
    borderGradient: 'linear-gradient(90deg, #e879f9, #22d3ee, #a3e635, #e879f9)',
    glowColor: '#e879f9',
    glowIntensity: 1.2,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#f0abfc',
    particleCount: 7,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'epic',
    coinCost: 850,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 29,
  },
  {
    id: 'golden_royalty',
    name: 'Golden Royalty',
    description: 'Luxurious gold leaf patterns shimmer and rotate around your profile',
    icon: '👑',
    animationType: 'gold_shimmer',
    frameStyle: 'legendary',
    borderColor: '#f59e0b',
    borderGradient: 'linear-gradient(135deg, #f59e0b, #fbbf24, #d97706, #fde68a)',
    glowColor: '#fbbf24',
    glowIntensity: 1.1,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#fde68a',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'legendary',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 30,
  },
  {
    id: 'diamond_prism',
    name: 'Diamond Prism',
    description: 'Prismatic diamond light refracts and sparkles around your avatar',
    icon: '💎',
    animationType: 'diamond_sparkle',
    frameStyle: 'legendary',
    borderColor: '#67e8f9',
    borderGradient: 'linear-gradient(135deg, #67e8f9, #c4b5fd, #f9a8d4, #fde68a)',
    glowColor: '#c4b5fd',
    glowIntensity: 1.3,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 10,
    hasSparkles: true,
    hasEnergyRings: true,
    rarity: 'mythic',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 31,
  },
  {
    id: 'shadow_void',
    name: 'Shadow Void',
    description: 'Dark energy swirls and pulses around your frame with purple void flames',
    icon: '🖤',
    animationType: 'smoke',
    frameStyle: 'legendary',
    borderColor: '#581c87',
    borderGradient: 'linear-gradient(135deg, #581c87, #7c3aed, #3b0764, #8b5cf6)',
    glowColor: '#8b5cf6',
    glowIntensity: 1.4,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#c4b5fd',
    particleCount: 9,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'mythic',
    coinCost: 1000,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 32,
    frameType: 'profile',
  },
  // ─── BROADCAST FRAMES (Stream Border Decorations) ─────────────────────
  // These frames wrap the entire broadcast layout as a decorative border
  {
    id: 'broadcast_neon',
    name: 'Neon Border',
    description: 'Pulsing neon border wraps around your entire stream',
    icon: '⚡',
    animationType: 'neon_glow',
    frameStyle: 'animated',
    borderColor: '#00ff88',
    borderGradient: 'linear-gradient(90deg, #00ff88, #ff00ff, #0088ff, #00ff88)',
    glowColor: '#00ff88',
    glowIntensity: 1.0,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#00ff88',
    particleCount: 5,
    hasSparkles: false,
    hasEnergyRings: true,
    rarity: 'epic',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 100,
    frameType: 'broadcast',
  },
  {
    id: 'broadcast_rainbow',
    name: 'Rainbow Stream',
    description: 'Flowing rainbow border for your broadcast',
    icon: '🌈',
    animationType: 'rainbow',
    frameStyle: 'premium',
    borderColor: '#ff0000',
    borderGradient: 'linear-gradient(90deg, #ff0000, #ff8800, #ffff00, #00ff00, #0088ff, #8800ff, #ff0000)',
    glowColor: '#ff00ff',
    glowIntensity: 0.8,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 6,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 101,
    frameType: 'broadcast',
  },
  {
    id: 'broadcast_gold',
    name: 'Golden Border',
    description: 'Luxurious gold shimmer around your stream',
    icon: '👑',
    animationType: 'gold_shimmer',
    frameStyle: 'premium',
    borderColor: '#ffd700',
    borderGradient: 'linear-gradient(135deg, #ffd700, #ffaa00, #ffd700, #ffe066)',
    glowColor: '#ffd700',
    glowIntensity: 1.0,
    animationSpeed: 'slow',
    hasParticles: true,
    particleColor: '#ffd700',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 102,
    frameType: 'broadcast',
  },
  {
    id: 'broadcast_fire',
    name: 'Inferno Stream',
    description: 'Animated flames dance around your broadcast border',
    icon: '🔥',
    animationType: 'fire',
    frameStyle: 'legendary',
    borderColor: '#ff4400',
    borderGradient: 'linear-gradient(180deg, #ff6600, #ff2200, #ff8800, #ff4400, #ffcc00)',
    glowColor: '#ff4400',
    glowIntensity: 1.2,
    animationSpeed: 'fast',
    hasParticles: true,
    particleColor: '#ffcc00',
    particleCount: 10,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'legendary',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 103,
    frameType: 'broadcast',
  },
  {
    id: 'broadcast_ice',
    name: 'Frost Stream',
    description: 'Icy crystals and snow swirl around your broadcast',
    icon: '❄️',
    animationType: 'ice',
    frameStyle: 'premium',
    borderColor: '#88ccff',
    borderGradient: 'linear-gradient(135deg, #88ccff, #ffffff, #aaddff, #88ccff)',
    glowColor: '#88ccff',
    glowIntensity: 1.0,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#ffffff',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'epic',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 104,
    frameType: 'broadcast',
  },
  {
    id: 'broadcast_hearts',
    name: 'Love Stream',
    description: 'Floating hearts surround your broadcast play area',
    icon: '💕',
    animationType: 'hearts',
    frameStyle: 'premium',
    borderColor: '#ec4899',
    borderGradient: 'linear-gradient(135deg, #ec4899, #f472b6, #db2777, #f9a8d4)',
    glowColor: '#f472b6',
    glowIntensity: 0.9,
    animationSpeed: 'normal',
    hasParticles: true,
    particleColor: '#f9a8d4',
    particleCount: 8,
    hasSparkles: true,
    hasEnergyRings: false,
    rarity: 'rare',
    coinCost: 500,
    isActive: true,
    isLimited: false,
    limitedQuantity: null,
    sortOrder: 105,
    frameType: 'broadcast',
  },
];

// ─── Helper: Get frame by ID ────────────────────────────────────
export function getFrameById(id: string): ProfileFrame | undefined {
  return LAUNCH_FRAMES.find(f => f.id === id);
}

// ─── Helper: Get frames by rarity ───────────────────────────────
export function getFramesByRarity(rarity: FrameRarity): ProfileFrame[] {
  return LAUNCH_FRAMES.filter(f => f.rarity === rarity);
}

// ─── Helper: Sort frames by rarity tier ─────────────────────────
export const RARITY_ORDER: Record<FrameRarity, number> = {
  common: 0,
  rare: 1,
  epic: 2,
  legendary: 3,
  mythic: 4,
  limited_edition: 5,
  founder: 6,
};

export function sortFramesByRarity(frames: ProfileFrame[]): ProfileFrame[] {
  return [...frames].sort((a, b) => RARITY_ORDER[a.rarity] - RARITY_ORDER[b.rarity]);
}
