import { matchPath } from 'react-router-dom'
import { getPhoneAdminRoute } from './phoneAdminRoutes'

const PHONE_NATIVE_ROUTE_PATTERNS = [
  '/phone',
  '/',
  '/auth',
  '/login',
  '/careers',
  '/go-live',
  '/mai-piks',
  '/broadcast',
  '/broadcast/setup',
  '/broadcast/summary/:id',
  '/auctions',
  '/troll-court',
  '/founder',
  '/store',
  '/coins',
  '/wallet',
  '/profile',
  '/notifications',
  '/mai-life',
  '/troll-animal-shelter',
  '/owner',
  '/following',
  '/following/:userId',
  '/following/:username',
  '/podcast',
  '/hytro',
  '/gaming/watch/:streamId',
  '/viewer',
  '/treelz',
  '/utromail',
  '/utromail/:threadId',
  '/admin',
  '/admin-mobile',
  '/rtcadminmonitor',
  '/support',
  '/safety',
  '/legal',
  '/jail',
  '/phone-secretary',
  '/phone-lead-officer',
  '/phone-troll-officer',
  '/phone-pastor',
  '/home',
  '/battles',
  '/live',
  '/leagues',
  '/explore',
  '/tcnn',
  '/community-wall',
  '/leaderboard',
  '/blocked-users',
  '/troll-up',
  '/profile/delete',
  '/treelz/upload',
  '/admin/users',
  '/admin/payouts',
  '/admin/reports',
  '/admin/moderation',
  '/admin/settings',
  '/admin/applications',
  '/search',
  '/profile/:username',
  '/live/:id',
  '/broadcast/:id',
  '/watch/:id',
  '/stream/:id',
  '/podcast/:id',
  '/troll-court/:id',
  '/court/:id',
  '/agency/:id',
  '/agency-apply/:id',
  '/tromail',
  '/tromail/:threadId',
  '/family/:id',
  '/government/:id',
  '/president/:id',
  '/secretary/:id',
  '/ceo-assistant-dashboard',
  '/ceo-assistant-dashboard/*',
]

export function hasPhoneNativeRoute(pathname: string): boolean {
  const matchesNativeRoute = PHONE_NATIVE_ROUTE_PATTERNS.some((pattern) =>
    matchPath({ path: pattern, end: true }, pathname),
  )

  if (matchesNativeRoute) return true

  return pathname.startsWith('/admin/') && getPhoneAdminRoute(pathname) !== null
}
